services:
  backend:
    image: node:20-bullseye-slim
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
      - ../node_modules:/app/node_modules
    network_mode: host
    command: ["npm", "run", "start:dev"]
    depends_on:
      - postgres
      - redis

  postgres:
    image: "postgres:16.3-alpine"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_ROOT: root

  redis:
    image: "redis:7-alpine"
    restart: always
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      REDIS_PASSWORD: password
